name: basic_server
channels:
  - conda-forge
  - anaconda
dependencies:
  # Python and package management itself
  - python=3.11
  - pip
  # Modules for setting up development environment
  - pylint
  - pytest
  - black
  - pydantic
  # Typically used modules
  - requests
  - orjson
  # Essential modules for the server
  - flask
  - flask-socketio
  - simple-websocket  # Without this, Socket.IO falls back to less efficient means than WebSocket
